### ISSUE TITLE
Error: failed to allocate DIO 14

### ISSUE THREAD

**Issue by PanicWaffleHead** [Thunderstamps/navx2workaround#1]
Hello, we are 2399 Fighting Unicorns. Thank you so much for sharing your code, however, there is an issue which is pasted below.

```
Failed to allocate DIO 14
Exception in thread "navXIOThread" edu.wpi.first.hal.util.AllocationException: Code: -1029
PWM or DIO 14 previously allocated.
Location of the previous allocation:
Location of the current allocation:
at edu.wpi.first.hal.SPIJNI.spiInitialize(Native Method)
at frc.robot.util.NavX.RegisterIO_SPI.resetSPI(RegisterIO_SPI.java:110)
at frc.robot.util.NavX.RegisterIO_SPI.read(RegisterIO_SPI.java:97)
at frc.robot.util.NavX.RegisterIO.getCurrentData(RegisterIO.java:126)
at frc.robot.util.NavX.RegisterIO.run(RegisterIO.java:71)
at frc.robot.util.NavX.AHRS$IOThread.run(AHRS.java:1271)
at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Thunderstamps** [comment]
Hello,

Is it possible you're creating more than one instance of the AHRS class?


On Mar 8, 2023 8:58 p.m., "PanicWaffleHead notifications-at-github.com |GitHub Thunderstamps/Allow Personal|" ***@***.***> wrote:

Hello, we are 2399 Fighting Unicorns. Thank you so much for sharing your code, however, there is an issue which is pasted below.

Failed to allocate DIO 14
Exception in thread "navXIOThread" edu.wpi.first.hal.util.AllocationException: Code: -1029
PWM or DIO 14 previously allocated.
Location of the previous allocation:
Location of the current allocation:
at edu.wpi.first.hal.SPIJNI.spiInitialize(Native Method)
at frc.robot.util.NavX.RegisterIO_SPI.resetSPI(RegisterIO_SPI.java:110)
at frc.robot.util.NavX.RegisterIO_SPI.read(RegisterIO_SPI.java:97)
at frc.robot.util.NavX.RegisterIO.getCurrentData(RegisterIO.java:126)
at frc.robot.util.NavX.RegisterIO.run(RegisterIO.java:71)
at frc.robot.util.NavX.AHRS$IOThread.run(AHRS.java:1271)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by maisieyanz** [comment]
> Hello, Is it possible you're creating more than one instance of the AHRS class? On Mar 8, 2023 8:58 p.m., "PanicWaffleHead notifications-at-github.com |GitHub Thunderstamps/Allow Personal|" ***@***.***> wrote: Hello, we are 2399 Fighting Unicorns. Thank you so much for sharing your code, however, there is an issue which is pasted below. Failed to allocate DIO 14 Exception in thread "navXIOThread" edu.wpi.first.hal.util.AllocationException: Code: -1029 PWM or DIO 14 previously allocated. Location of the previous allocation: Location of the current allocation: at edu.wpi.first.hal.SPIJNI.spiInitialize(Native Method) at frc.robot.util.NavX.RegisterIO_SPI.resetSPI(RegisterIO_SPI.java:110) at frc.robot.util.NavX.RegisterIO_SPI.read(RegisterIO_SPI.java:97) at frc.robot.util.NavX.RegisterIO.getCurrentData(RegisterIO.java:126) at frc.robot.util.NavX.RegisterIO.run(RegisterIO.java:71) at frc.robot.util.NavX.AHRS$IOThread.run(AHRS.java:1271) at java.base/java.lang.Thread.run(Unknown Source) — Reply to this email directly, view it on GitHub<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2FThunderstamps%2Fnavx2workaround%2Fissues%2F1&data=eJw1jDEPgyAUhH-NjEbRqgwMXZxMmjSduj2BFqL4GnhUf35xaHLL3Xd3SnY19MC7pufDUDEtDc1YKmBeipkut_ppJnHXLMpV49FiG5QXL4FUtFXcDCzGg1tLhZ4FGRUSlbt1tKJacuN_lqQl-sSiuRZ8zHo7smk-V9k8bNq0CZHA5wofN_gefMewQMBMcuJiTOZE9Q_YGzt9>, or unsubscribe<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5DGI6E2H7FBTP6BCG6BTDTW3E2LBANCNFSM6AAAAAAVUPO3BM&data=eJw1jMsOgjAURL8GdhItWGTRBVVRE19R1MRdW6o0AtfQ2-jnW02czOZMZkYxOhKpIDROyWQyDCumUUKkRNiyTOJ4N7rqdXaoQsuaCt4JJL1qs1sGGCRD22nx0K0wTaSgDXtmFSBGr9pgA-rhG_8zx2rEpw3iPCCF991g7eR35aEDNDejBBrorGfXWSet6o3UA-Gw9lE-ni1WdE6WacHLPeXTBeXlrLzEc7Lm-Xa6LY4bmv90Pu13Md98ACB1Rck%>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hello, 
You are correct, we accidentally created two instances of the AHRS class. We were able to resolve our error after fixing that issue. Thank you so much for your help!
